app: puppeteer-audit-service
services:
  - name: audit-service
    docker:
      image: node:18-slim
    env:
      - NODE_ENV=production
      - PORT=8080
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - API_KEY=${API_KEY}
      - CALLBACK_URL=${CALLBACK_URL}
      - CHROME_EXECUTABLE_PATH=/usr/bin/chromium
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - MAX_CONCURRENT_JOBS=3
      - REQUEST_TIMEOUT=300000
      - MEMORY_LIMIT=512
    ports:
      - port: 8080
        protocol: http
    regions:
      - was  # Washington (US East)
    instance_type: small  # 1 vCPU, 1GB RAM
    autoscaling:
      min: 0  # Scale to zero when not in use
      max: 3  # Scale up to 3 instances under load
    health_check:
      http:
        path: /health
        port: 8080
      initial_delay: 30
      timeout: 10
      interval: 30
      retries: 3
